### ISSUE TITLE
Suggestion - Chat Group Formatting

### ISSUE THREAD

**Issue by featxeven** [NoximityCollective/RemmyChat#3]
I'm pretty sure the main feature of RemmyChat are the channels, but it would be great to also include optional group-based formatting alongside channels. For example, the config could be extended like this:
```
channels:
  global:
    format: "<#F8F9FA>[Global]</#F8F9FA>"
    permission: '' # Empty means everyone can use
    radius: -1 # -1 means global chat
  
  local: ...

groups:
  owner:
    format: |-
      <hover:show_text:'<#778899>Player information
      <#F8F9FA>Name: <#E8E8E8><player>
      <#F8F9FA>Click to message'><click:suggest_command:/msg <player> > %remmychat_channel% <red>[OWNER]</red><#4A90E2><displayname></click></hover><#778899>: <#F8F9FA><message>
  admin: ...
```

The placeholder %remmychat_channel% could be replaced with an internal placeholder, but that's up to the developer.
So out of this, the main display would be the group formatting. And the soft dependency could be LuckPerms.
